In [1]:
import pandas as pd

In [2]:
pd.DataFrame([1,2,3],columns=['A'],index=['A','B','C'])

   A
A  1
B  2
C  3

In [3]:
pd.DataFrame((1,2,3,))

   0
0  1
1  2
2  3

In [8]:
pd.DataFrame({"months":["jan","feb"],"sales":[20,30]})

  months  sales
0    jan     20
1    feb     30

In [9]:
pd.DataFrame({"months":["jan","feb"]})

  months
0    jan
1    feb

In [10]:
import numpy as np
np.random.seed(121)
pd.DataFrame(np.random.randint(0,10,(3,3)))

   0  1  2
0  2  5  8
1  4  1  4
2  3  0  2

In [ ]:
df=pd.DataFrame(np.random.randint(0,10,(3,3)))

In [20]:
df

   0  1  2
0  2  5  8
1  4  1  4
2  3  0  2

In [13]:
"A B C".split()

['A', 'B', 'C']

In [22]:
np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)),columns="A B C".split(),index='P Q R'.split())
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [23]:
import pandas as pd
df = pd.read_csv(r"C:\Users\hasan\OneDrive\Desktop\Superstore sales dataset.csv")
# print(df.head())

In [24]:
df.shape

(9994, 21)

In [26]:
df.columns
df.head(2)
df.tail()
df.index

RangeIndex(start=0, stop=9994, step=1)

In [27]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [31]:
df[["Row ID","Order ID","Sales"]].head(2)

   Row ID        Order ID   Sales
0       1  CA-2016-152156  261.96
1       2  CA-2016-152156  731.94

df.iloc[rows,columns]

In [32]:
df.iloc[2:8,[2,5,7]]

   Order Date Customer ID    Segment
2   12/6/2016    DV-13045  Corporate
3  11/10/2015    SO-20335   Consumer
4  11/10/2015    SO-20335   Consumer
5    9/6/2014    BH-11710   Consumer
6    9/6/2014    BH-11710   Consumer
7    9/6/2014    BH-11710   Consumer

In [33]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [34]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [35]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [36]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [37]:
np.finfo(np.float16).min

np.float16(-6.55e+04)

In [38]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [39]:
df.select_dtypes(include=['str']).shape

(9994, 15)

In [40]:
df.shape

(9994, 21)

In [41]:
df.select_dtypes(include=['int64','float64']).shape

(9994, 6)

In [42]:
subset_df=df.iloc[0:5,0:5].copy()

In [43]:
subset_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode'], dtype='str')

In [44]:
subset_df[['Row ID','Order ID','Ship Mode','Ship Date']].min()

Row ID                    1
Order ID     CA-2016-138688
Ship Mode      Second Class
Ship Date        11/11/2016
dtype: object

In [45]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [46]:
df['Ship Mode'].str.upper().head(2)

0    SECOND CLASS
1    SECOND CLASS
Name: Ship Mode, dtype: str

In [47]:
df['Ship Mode'].str.lower().head(2)

0    second class
1    second class
Name: Ship Mode, dtype: str

In [48]:
df['Ship Mode'].str.capitalize().head(2)

0    Second class
1    Second class
Name: Ship Mode, dtype: str

In [49]:
df['Ship Mode'].str.title().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [50]:
"data Science".capitalize()

'Data science'

In [51]:
df['Ship Mode'].str.len().head(2)

0    12
1    12
Name: Ship Mode, dtype: int64

In [52]:
df['Ship Mode'].str.len().tail(2)

9992    14
9993    12
Name: Ship Mode, dtype: int64

In [53]:
df['Ship Mode'].str.strip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [54]:
df['Ship Mode'].str.lstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [55]:
df['Ship Mode'].str.rstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [56]:
df['Ship Mode'].str.split(" ").str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [57]:
"91-733833".split("-")

['91', '733833']

In [58]:
"Data Science".split()

['Data', 'Science']

In [59]:
"data science".split("a")

['d', 't', ' science']

In [60]:
df['Ship Mode'].str.count("Second")

0       1
1       1
2       1
3       0
4       0
       ..
9989    1
9990    0
9991    0
9992    0
9993    1
Name: Ship Mode, Length: 9994, dtype: int64

In [61]:
df['Ship Mode'].str.pad(width=20,side='left',fillchar="-")

0       --------Second Class
1       --------Second Class
2       --------Second Class
3       ------Standard Class
4       ------Standard Class
                ...
9989    --------Second Class
9990    ------Standard Class
9991    ------Standard Class
9992    ------Standard Class
9993    --------Second Class
Name: Ship Mode, Length: 9994, dtype: str